FROM debian:bookworm-slim

RUN apt update && apt install -y \
    curl \
    iptables

RUN curl -s https://install.crowdsec.net | sh

RUN apt install crowdsec-firewall-bouncer-iptables -y &&\
    rm -rf /var/lib/{apt,dpkg,cache,log}/

COPY --chmod=755 ./run.sh /run.sh

CMD [ "/run.sh" ]
